project:
  type: website

website:
  title: "GM0ESS"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Members
      - href: cairngorm-awards.qmd
        text: Cairngorm Awards

format:
  html:
    theme:
      - pandoc
      - brand
    css: styles.css
    toc: true



